# Dockerfile (루트 디렉토리에 위치)

FROM node:22 AS build
WORKDIR /app

# 상대 경로로 변경
COPY ./package.json ./yarn.lock ./
COPY ./turbo.json ./
COPY ./tsconfig.base.json ./
COPY ./apps/web/dayprint .

RUN yarn install --frozen-lockfile
RUN yarn build

FROM node:22-alpine
WORKDIR /app

COPY --from=build /app/dist /app/dist

RUN npm install -g serve

CMD ["serve", "-s", "dist", "-l", "3000"]
EXPOSE 3000
