version: '3.8'

services:
  nginx:
    build:
      context: ./
    ports:
      - '80:80'
    networks:
      - universe-network

  dayprint:
    build:
      context: ./apps/web/dayprint
    networks:
      - universe-network

networks:
  app-network:
    driver: bridge
