version: "3.8"

services:
  nginx:
    build:
      context: ./
    ports:
      - "80:80"
    networks:
      - universe-network

  universe:
    build:
      context: ./apps/web/universe
    networks:
      - universe-network

  admin:
    build:
      context: ./server/admin
    networks:
      - universe-network

networks:
  app-network:
    driver: bridge
