services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dayprint
    container_name: nginx
    networks:
      - universe

  dayprint:
    image: jnsia/dayprint
    ports:
      - '3000:3000'
    container_name: dayprint
    networks:
      - universe

networks:
  universe:
    external: true
