services:
  nginx:
    build:
      context: ./infra/nginx
    ports:
      - '80:80'
    depends_on:
      - dayprint
    networks:
      - universe

  dayprint:
    build:
      context: .
      dockerfile: dockerfile.dayprint
    ports:
      - '3000:3000'
    networks:
      - universe

networks:
  universe:
    driver: bridge
