FROM node:22 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install -g yarn
RUN yarn install

COPY . .
RUN npm run build

FROM node:22
WORKDIR /app
COPY --from=build /app/build /app/build

COPY package*.json ./
RUN yarn install --only=production

CMD ["npx", "serve", "-s", "build", "-l", "3000"]
EXPOSE 3000
