FROM node:22 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install -g yarn
RUN yarn install

COPY . .
RUN npm run build

FROM node:22
WORKDIR /app

COPY --from=build /app/.next .next
COPY --from=build /app/public public
COPY --from=build /app/package*.json ./

RUN npm install --only=production
CMD ["yarn", "start"]
EXPOSE 3000
