name: Build and Push Docker Image - Dayprint

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/dayprint/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/web/dayprint/**'
  workflow_dispatch:

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/dayprint
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Debug - List files in root
        run: |
          echo "Files in root:"
          ls -la
          echo "Files in packages:"
          ls -la packages/ || echo "packages directory not found"
          echo "Files in apps/web/dayprint:"
          ls -la apps/web/dayprint/ || echo "apps/web/dayprint directory not found"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Create .env for build
        run: |
          {
            echo "VITE_APP_SUPABASE_KEY=${{ secrets.VITE_APP_SUPABASE_KEY }}"
          } > .env

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dayprint
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
